### ISSUE TITLE
Error on receiving response if special chars are used in request body (diacritics)

### ISSUE THREAD

**Issue by codexms** [robert52/quark#1]
SyntaxError: Unexpected end of input
at Object.parse (native)
at IncomingMessage.<anonymous> (.../node_modules/quark/lib/http-transport.js:90:27)
at IncomingMessage.emit (events.js:129:20)
at stream_readable.js:908:16
at process.tickCallback (node.js:355:11)

**Comment by robert52** [comment]
Yes @KFreak  String.prototype.length was not suitable for that situation.
